Searching Algorithm/Ternary Search.cpp file
Implementation of Search algorithm in cpp
=> Ternary Search.cpp file added

Binary Tree/same tree leetcode.cpp
Problem statement link :- https://leetcode.com/problems/same-tree/
=> Create same tree leetcode.cpp

Array/equilibrium index.cpp
Problem statement link :- https://leetcode.com/problems/find-pivot-index/
=> Create equilibrium index.cpp

Recursion/getMazePaths.cpp
I would like to add knights tour using recursion ...pepcoding solution!
Thankyou so much!
=> add code of knights tour using recursion

Array/fibbRecursion.cpp
Hii @raushanraj358  
I have added a program to find a program to find fibbonacci recursively .
Kindly please make accept my pr if find it helpful
=> added program to find the fibbonacci recursively

Recursion/floodFill.cpp
I would like to add code of Flood Fill problem 733 Leetcode
I have provided simple recursive solution to the problem.
=> Added code of Leetcode Problem:733 Flood Fill

Priority Queue/trapping-rain-water.cpp
Trapping Rain Water in a Matrix
=> Trapping Rain Water in a Matrix

Priority Queue/indexed-priority-queue.cpp
Indexed Priority Queue with Implementation
=> Indexed-Priority-Queue

Priority Queue/RabbitHouse.cpp
Rabbit House | Google Kickstart 2021 Round A
=> Priority-Queue: Rabbit House

Array/minimize-subarray.cpp
Minimize subarray increments / decrements required to reduce all array elements to 0
=> Minimize-subarray

maximize-arr-sum.cpp
Maximize array sum by replacing equal adjacent pairs by their sum and X respectively
=> Maximize-subarray

count-quadruples.cpp
Count quadruples(i, j, k, l) in an array such that i < j < k < l and arr[i] = arr[k] and arr[j] = arr[l]
=> Count Quadruples

Array/check-coprime.cpp
Check if all the pairs of an array are coprime with each other
=> Check Coprime

Dynamic programming/catalan-number.cpp
=> Nth Catalan number

Backtracking/rat-in-a-maze.cpp.cpp
Backtracking: Rat in a maze solution
=> Backtracking: Rat in a maze solution

Binary Tree/sum-of-leaf-nodes.cpp
CPP program : Sum of leaf nodes at each horizontal level in a binary tree
=> Sum of leaf nodes at each horizontal level

Binary Tree/check-binary-tree-is-sum-tree.cpp
CPP program to check binary tree is a sum tree or not
=> Check binary tree is a sum tree

Binary Tree/symmetric tree.cpp
Given a binary tree, check whether it is a mirror of itself.
=> Symmetric tree

Binary Tree/Boundary-traversal-of-Binary-Tree.cpp
Added boundary traversal of binary tree with comments. Issue(#81)
Kindly review and merge the PR and add the hacktoberfest label. @raushanraj358
=> Added boundary traversal of binary tree

NftMinter.sol
by using this smart contract a person can mint his or her own nft
=> Nft Generator

Linked List/intersection_point_in_Y_Shapped_Linked_list.cpp
i have made the PR for Intersection-Point-in-Y-Shapped-Linked-Lists. pls review it and merge the PR and close the issue #82.
kindly add the hactoberfest level.
=> Intersection-Point-in-Y-Shapped-Linked-Lists

Inheritance/method overriding.java, Priority Queue/queue using two stacks.c, stack/stack-using-array.cpp
=> Shivanisingh1809 patch 3

Searching Algorithm/Sublist_Search.cpp
Hello, Added the Sublist search program in C++ language, Please do review and merge it.
=> Added the Sublist search program in C++ language.

stack/balanced_parenthesis_using_stack.cpp
I have Added a balanced parenthesis problem in CPP using stack in stack directory.
=> Added Famous stack problem in cpp

Count digit & Sum of Digit.c
=> Count digit & Sum of Digit.
